# Generated by Django 2.1.1 on 2018-09-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='data_added',
        ),
    ]
